### ISSUE TITLE
Practice Nested Repeaters

### ISSUE THREAD

**Issue by ihugya1** [ihugya1/DMIT-2018-Workbook-IanHugya#1]
Create a page that shows our suppliers and the products they offer. OI will need to see the information in the following "structure"

- **Supplier** 💯 
- Company Name 👍 
- Contact Name 🥇 
- Phone Number 🔢 
- **Product Summary** 👎 
- Product Name 💯 
- Category Name 👍 
- Unit Price 🥇 
- Quantity/Unit 🔢 

##Tasks
- [ ] Create  LINQ Queryin LinqPad
- [ ] Create  classes for the **Read Model**
- [ ] Copy/Adapt LinqPad stuff
- [ ] Create  page with nested repeater
